### ISSUE TITLE
Website says 40, inaccurate

### ISSUE THREAD

**Issue by pbiggar** [TechForPalestine/website#10]
We're way more than 40 people now, though I wouldn't say that all 1488 in the discord have joined the movement. Could do with some different wording - I'm not sure if saying "1000" is better than saying 40. Or maybe it's fine?

**Comment by mudssrali** [comment]
> We're way more than 40 people now, though I wouldn't say that all 1488 in the discord have joined the movement. Could do with some different wording - I'm not sure if saying "1000" is better than saying 40. Or maybe it's fine?

Can we do poll in discord to get an idea how many people have joined the movement?  Or we can say "100+", "1000+" working.

**Comment by pbiggar** [comment]
It says there's 1700 on the server

**Comment by mudssrali** [comment]
> It says there's 1700 on the server

Was out sick. Then we can say `1,500+`
