### ISSUE TITLE
Call to action for non-tech visitors

### ISSUE THREAD

**Issue by Tarctic** [TechForPalestine/website#11]
I added the TFP banner to one of my websites aimed at helping users learn Arabic. However, I then realized that the majority of the users who use my website are unlikely to be involved in tech. These people will have nothing to do after visiting the TFP website. 

My suggestion is to add a different call to action for non tech visitors, below the three buttons like this:

<img width="300" alt="image" src="https://github.com/TechForPalestine/website/assets/85291498/edd297df-6e9f-458a-bcc2-e04aeac8f1f2">

As to where the link takes them, it can be to a list of resources that help Gaza, such as e-sims, donations, petitions etc. Or a place for writers, artists etc. where they can put their skills to use. We can discuss on what the call to action should be.

**Comment by pbiggar** [comment]
Thanks! We are working on a different page for the link to go to. It goes to /learn-more and we'll put a page there with better content. I'll leave this open for now, and we can see in a week what the situation is like.

**Comment by janajri** [comment]
Banner is now directing people to /learn-more, updates-in-progress. Closing this for now.
