### ISSUE TITLE
Some companies to add to the list of boycott

### ISSUE THREAD

**Issue by ptrace** [TechForPalestine/website#12]
This site lists some more companies that we should boycott
https://bdsmovement.net/Act-Now-Against-These-Companies-Profiting-From-Genocide

For example:
Intel, Hyundai, Volvo, CAT, Google, Amazon, Airbnb, Booking, Expedia, McDonalds, Burger King, WIX, HP

I can also add to the list:
Microsoft (Have offices on on the destroyed palestinian village Al-Haram)
NVIDIA (Have offices on on the destroyed palestinian village Al-Shaykh Muwannis)

**Comment by pbiggar** [comment]
Thanks! Boycotts are done in different repos, reach out there:
- https://github.com/TechForPalestine/boycott-israeli-tech-companies-dataset
- https://github.com/TechForPalestine/boycott-israeli-consumer-goods-dataset
