### ISSUE TITLE
use rss icon for "updates"

### ISSUE THREAD

**Issue by pbiggar** [TechForPalestine/website#21]
can we use the RSS icon for the updates link in the footer.

Something like this?
<img width="175" alt="Screenshot 2024-01-20 at 9 21 53 PM" src="https://github.com/TechForPalestine/website/assets/181762/7b926fa8-6b28-429d-a901-a196b49f46f8">

**Comment by hanadi92** [comment]
This one is given by mdi 

<img width="198" alt="Screenshot 2024-01-21 at 12 19 50 PM" src="https://github.com/TechForPalestine/website/assets/19797958/7a85b538-d631-4236-826e-312083645824">

wdyt?

**Comment by pbiggar** [comment]
Works for me.
