### ISSUE TITLE
Perhaps add troubleshooting `(i)` to discord invite

### ISSUE THREAD

**Issue by pbiggar** [TechForPalestine/website#24]
Multiple people have told me they've had issues signing up for discord. In each case, signups have appeared to be working. Today, someone mentioned that signing out of discord in their browser solved the issue for them.

Perhaps a little tooltip, or an info icon with a tooltip, might be helpful here?

**Comment by thamudi** [comment]
Does this work?

I tried to make it as less intrusive as possible.

https://github.com/TechForPalestine/website/assets/18720062/6b461068-5f5c-455f-ae86-a5d59996b8eb

**Comment by pbiggar** [comment]
@janajri wdty?

**Comment by janajri** [comment]
Works for me, we should consider adding a support e-mail as well as a way to reach out for help.

**Comment by thamudi** [comment]
It can be added as a new button which sends an email

<img width="535" alt="image" src="https://github.com/TechForPalestine/website/assets/18720062/a2d70fb5-52dc-42f7-8da6-80967704a24f">

**Comment by janajri** [comment]
I was thinking something more subtle, but that's out of scope anyway. Feel free to submit a PR with the tooltip addition
