### ISSUE TITLE
Missing link to blog on homepage

### ISSUE THREAD

**Issue by webzetetic** [TechForPalestine/website#25]
We should have a link to the blog (updates.techforpalestine.org) on the home page.

**Comment by hanadi92** [comment]
Hey, it's in the footer. The rss icon. Or do you suggest somewhere more prominent?

**Comment by webzetetic** [comment]
Yeah I think it should be more prominent. I think the average user wouldn't look there. (Speaking as an average user!)

**Comment by janajri** [comment]
Added to the top level navigation, should be a better now
