### ISSUE TITLE
The image at /learn-more resolution is too high .

### ISSUE THREAD

**Issue by issafy** [TechForPalestine/website#26]
Hi. I was trying to access  the ```learn-more``` page and my browser crashed a few times. I think this is happening because of the resolution of the image.
I suggest if possible to display a down-scaled version of the image to facilitate web browsing on the page.

Regards

**Comment by pbiggar** [comment]
Good point, thanks. If you make a PR I'm sure we'd merge that.

**Comment by issafy** [comment]
Okay cool. Thanks.
